theme: modern-resume-theme
# Site settings
name: Public Resume
resume_title: React UI Developer
# Update with your GitHub username and repo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<your-github-username>.github.io/<repository-name>"
# Social Links
github_username: <your-github-username>
# Build settings
markdown: kramdown
